/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package controller;

/**
 *
 * @author Ly Tinh Nhiem
 */
public class MenuPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form MenuPanel2
     */
    public MenuPanel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTrangChu = new controller.CustomButton();
        btnGiaoDich = new controller.CustomButton();
        btnHoaDon = new controller.CustomButton();
        btnDoiHang = new controller.CustomButton();
        btnNhanVien = new controller.CustomButton();
        btnKhachHang = new controller.CustomButton();
        btnNhaCungCap = new controller.CustomButton();
        btnSanPham = new controller.CustomButton();
        btnChiTietSanPham = new controller.CustomButton();
        btnNhapHang = new controller.CustomButton();
        btnKhuyenMai = new controller.CustomButton();
        btnThongKe = new controller.CustomButton();
        btnThoat = new controller.CustomButton();

        setMaximumSize(new java.awt.Dimension(150, 810));
        setMinimumSize(new java.awt.Dimension(150, 810));
        setPreferredSize(new java.awt.Dimension(250, 810));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logox75.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setAlignmentY(0.0F);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 250, 50));

        btnTrangChu.setText("Trang chủ");
        btnTrangChu.setAlignmentY(0.0F);
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });
        add(btnTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 55));

        btnGiaoDich.setText("Giao dịch");
        btnGiaoDich.setAlignmentY(0.0F);
        add(btnGiaoDich, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, 250, 55));

        btnHoaDon.setText("Hóa đơn");
        btnHoaDon.setAlignmentY(0.0F);
        add(btnHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 250, 55));

        btnDoiHang.setText("Đổi hàng");
        btnDoiHang.setAlignmentY(0.0F);
        add(btnDoiHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 245, 250, 55));

        btnNhanVien.setText("Nhân viên");
        btnNhanVien.setAlignmentY(0.0F);
        add(btnNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 55));

        btnKhachHang.setText("Khách hàng");
        btnKhachHang.setAlignmentY(0.0F);
        add(btnKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 355, 250, 55));

        btnNhaCungCap.setText("Nhà cung cấp");
        btnNhaCungCap.setAlignmentY(0.0F);
        add(btnNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 250, 55));

        btnSanPham.setText("customButton1");
        btnSanPham.setAlignmentY(0.0F);
        add(btnSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 465, 250, 55));

        btnChiTietSanPham.setText("customButton1");
        btnChiTietSanPham.setAlignmentY(0.0F);
        add(btnChiTietSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 250, 55));

        btnNhapHang.setText("customButton1");
        btnNhapHang.setAlignmentY(0.0F);
        add(btnNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 575, 250, 55));

        btnKhuyenMai.setText("customButton1");
        btnKhuyenMai.setAlignmentY(0.0F);
        add(btnKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 250, 55));

        btnThongKe.setText("customButton1");
        btnThongKe.setAlignmentY(0.0F);
        add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 685, 250, 55));

        btnThoat.setText("customButton1");
        btnThoat.setAlignmentY(0.0F);
        add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 250, 55));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrangChuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controller.CustomButton btnChiTietSanPham;
    private controller.CustomButton btnDoiHang;
    private controller.CustomButton btnGiaoDich;
    private controller.CustomButton btnHoaDon;
    private controller.CustomButton btnKhachHang;
    private controller.CustomButton btnKhuyenMai;
    private controller.CustomButton btnNhaCungCap;
    private controller.CustomButton btnNhanVien;
    private controller.CustomButton btnNhapHang;
    private controller.CustomButton btnSanPham;
    private controller.CustomButton btnThoat;
    private controller.CustomButton btnThongKe;
    private controller.CustomButton btnTrangChu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
